### ISSUE TITLE
No temp mail file incluied

### ISSUE THREAD

**Issue by ADylax** [Vinyzu/DiscordGenerator#10]
from TempMail import TempMail
ModuleNotFoundError: No module named 'TempMail'

**Comment by Vinyzu** [comment]
Did you installed all the requierements?
You can check this specific package with
`pip show tenpmail-lol`

**Comment by D4yno** [comment]
Seems like that library doesn't work for all, i keep unistalling and reinstalling but no luck it throws "ModuleNotFoundError: No module named 'TempMail'"

Also on captcha when you click to solve - it automatically closes after reading the captcha question: lion dog, etc
It doesn't wait untill full captcha is shown

**Comment by Vinyzu** [comment]
I will contact the creator of the package as some people reported this issue.

The captcha gets closed because the ai doesnt support some tasks/captcha types.

**Comment by alexanderepolite** [comment]
> I will contact the creator of the package as some people reported this issue.
> 
> The captcha gets closed because the ai doesnt support some tasks/captcha types.

@aimarket

**Comment by D4yno** [comment]
Make an exception on failed captcha/tasks :D great contribution by the way, i knew playwright had potential and the way you have modified the whole thing is just genius.

**Comment by CrazyKnifeAim1** [comment]
> Seems like that library doesn't work for all, i keep unistalling and reinstalling but no luck it throws "ModuleNotFoundError: No module named 'TempMail'"
> 
> Also on captcha when you click to solve - it automatically closes after reading the captcha question: lion dog, etc It doesn't wait untill full captcha is shown

i fixed it change your imports to from TempMail import tempMail it should work otherwise locate where the tempmail dll is hidden

**Comment by aimarket** [comment]
> > I will contact the creator of the package as some people reported this issue.
> > The captcha gets closed because the ai doesnt support some tasks/captcha types.
> 
> @aimarket
> 
> Edit: seems to be working for me. I'm not too sure how Python works, but the [basic usage in the readme](https://github.com/tempmail-lol/api-python) seems to work.

As mentioned in the reply, following the [README](https://github.com/tempmail-lol/api-python) should workout just fine.

Ex.
```py
from TempMail import TempMail #imports everything from TempMail library

inbox = TempMail.generateInbox() #returns an Inbox object with Email and Token

print("Email Address: "+ inbox.address) #View output below
print("Authorization Token: "+ inbox.token)
```

**Comment by CrazyKnifeAim1** [comment]
> 

getting an error for that

**Comment by aimarket** [comment]
> 

I would like to see the error message.

**Comment by CrazyKnifeAim1** [comment]
> ```python
> 
> inbox = TempMail.generateInbox() #returns an Inbox object with Email and Token
> 
> print("Email Address: "+ inbox.address) #View output below
> print("Authorization Token: "+ inbox.token)
> ```



> > 
> 
> I would like to see the error message.

C:\Users\forst\Downloads\NiggaGenerator (do not share)\DiscordGenerator-main>main.py
Traceback (most recent call last):
  File "C:\Users\forst\Downloads\NiggaGenerator (do not share)\DiscordGenerator-main\main.py", line 34, in <module>
    inbox = TempMail.generateInbox() #returns an Inbox object with Email and Token
AttributeError: module 'TempMail' has no attribute 'generateInbox'

**Comment by aimarket** [comment]
> from TempMail import TempMail ModuleNotFoundError: No module named 'TempMail'

Type `pip list` in the terminal and see if `tempmail-lol           1.1.0` is in the list.

**Comment by Vinyzu** [comment]
Should be fixxed with newest version.
Update your code.
