### ISSUE TITLE
Token locked

### ISSUE THREAD

**Issue by luckyoi** [Vinyzu/DiscordGenerator#11]
So all tokens i create using premium proxy list, gets locked after generating it. Any solution?

**Comment by PineapleTeam** [comment]
Its normal mate I got 10 locked and 3 unlocked

**Comment by luckyoi** [comment]
Yeh but the console closes each time it locks to token? And when using it without proxies, it works good (until my IP gets blacklisted) and when I put more then 2 threads while using proxies, i get this error https://cdn.discordapp.com/attachments/1010634798156480522/1010972948397555833/unknown.png

**Comment by PineapleTeam** [comment]
Try to use proxies from webshare.io i use the free plan and it works normal

**Comment by luckyoi** [comment]
well, not when trying to use those proxies, I instantly get those errors from the picture I sent above

**Comment by PineapleTeam** [comment]
i got that too before but when i change my proxies it becomes normal

**Comment by luckyoi** [comment]
weird how it doesn't work on premium proxies...

**Comment by PineapleTeam** [comment]
did your cmd close after the token locked?

**Comment by luckyoi** [comment]
![image](https://user-images.githubusercontent.com/106918177/185807272-6a44ff92-5dc1-4668-a3a7-976e20367593.png)
So this is what I get after aprox 10 minutes and it's stuck at that last error, ¨while when not using any proxies, it atleast tries again and again

**Comment by luckyoi** [comment]
ok, i guess its not locket,  just slow but all it gives in output is captcha solution was incorrect or another is needed

**Comment by SlotthCode** [comment]
im getting an error
'NoneType' object has no attribute 'strip'

**Comment by luckyoi** [comment]
[message (1).txt](https://github.com/Vinyzu/DiscordGenerator/files/9389827/message.1.txt)
update main.py with this, it should help i think

**Comment by Vinyzu** [comment]
> [message (1).txt](https://github.com/Vinyzu/DiscordGenerator/files/9389827/message.1.txt)
> update main.py with this, it should help i think

Please make a pull request.

**Comment by Vinyzu** [comment]
> im getting an error
> 'NoneType' object has no attribute 'strip'

Update to newest version please

**Comment by Vinyzu** [comment]
> ![image](https://user-images.githubusercontent.com/106918177/185807272-6a44ff92-5dc1-4668-a3a7-976e20367593.png)
> So this is what I get after aprox 10 minutes and it's stuck at that last error, ¨while when not using any proxies, it atleast tries again and again

The ai isnt updated since some time now. Im waiting for updates but cant to anything rn bout it.
Im also training my own ai rn ;:D.

**Comment by SlotthCode** [comment]
> > im getting an error
> > 'NoneType' object has no attribute 'strip'
> 
> Update to newest version please

i did and still i make a pull request of the error being fixed

**Comment by Vinyzu** [comment]
Ill close this issue, because i cant do anything about the issues mentioned here rn. (and somethings are also outdated by new versions)
If you feel like there is a thing i can do rn about your issue/error, feel free to open a new issue!
