### ISSUE TITLE
generate.inbox error

### ISSUE THREAD

**Issue by CrazyKnifeAim1** [Vinyzu/DiscordGenerator#13]
module 'TempMail' has no attribute 'generateinbox' 

dont know what to do help

**Comment by aimarket** [comment]
refer to [issue-1345422608](https://github.com/Vinyzu/DiscordGenerator/issues/10#issue-1345422608)

**Comment by CrazyKnifeAim1** [comment]
yeah?

**Comment by aimarket** [comment]
Could you share your `pip list` output?

**Comment by CrazyKnifeAim1** [comment]
> Could you share your `pip list` output?

how do i show that exactly?
 ive never done it before

**Comment by CrazyKnifeAim1** [comment]
> > Could you share your `pip list` output?
> 
> how do i show that exactly? ive never done it before

nvm im stupid

**Comment by CrazyKnifeAim1** [comment]
> Could you share your `pip list` output?

Package            Version
------------------ -----------
aioconsole         0.5.0
aiofiles           0.6.0
aiohttp            3.7.4.post0
aiosqlite          0.17.0
animec             0.4.2
anyio              3.6.1
appdirs            1.4.4
async-generator    1.10
async-timeout      3.0.1
asyncio            3.4.3
asyncio-extras     1.3.2
asyncpraw          7.5.0
asyncprawcore      2.3.0
attrs              22.1.0
beautifulsoup4     4.11.1
Brotli             1.0.9
bs4                0.0.1
certifi            2022.6.15
cffi               1.15.1
chardet            4.0.0
charset-normalizer 2.1.0
choice             0.1
colorama           0.4.5
discord.py         1.7.3
discord-webhook    0.16.3
discum             1.4.1
disputils          0.2.0
Faker              14.1.0
ffmpeg             1.4
filetype           1.1.0
greenlet           1.1.2
h11                0.12.0
httpcore           0.15.0
httpx              0.23.0
idna               3.3
imageio            2.21.1
importlib-metadata 4.12.0
lxml               4.9.1
MouseInfo          0.1.3
multidict          6.0.2
mutagen            1.45.1
networkx           2.8.5
numpy              1.21.6
opencv-python      4.5.5.64
outcome            1.2.0
packaging          21.3
Paginator          0.5.1
Pillow             9.2.0
pip                22.2.2
playwright         1.22.0
playwright-stealth 1.0.5
PyAutoGUI          0.9.53
pycparser          2.21
pycryptodomex      3.15.0
pyee               8.1.0
pyfade             6.0
pyfiglet           0.8.post1
PyGetWindow        0.0.9
PyMsgBox           1.0.9
pyparsing          3.0.9
pyperclip          1.8.2
pyppeteer          1.0.2
PyRect             0.2.0
PyScreeze          0.1.28
PySocks            1.7.1
python-dateutil    2.8.2
pytweening         1.0.4
PyWavelets         1.3.0
PyYAML             6.0
random-user-agent  1.0.1
requests           2.28.1
requests-toolbelt  0.9.1
rfc3986            1.5.0
rule34             1.8.1
scikit-image       0.19.3
scipy              1.7.3
selenium           4.4.3
setuptools         63.2.0
six                1.16.0
sniffio            1.2.0
sortedcontainers   2.4.0
soupsieve          2.3.2.post1
tempMail           3.0
tempmail-lol       1.1.0
tempmail-py        1.0
tifffile           2022.8.12
tqdm               4.64.0
trio               0.21.0
trio-websocket     0.9.2
typing_extensions  4.3.0
ua-parser          0.15.0
update-checker     0.18.0
urllib3            1.26.11
websocket-client   0.59.0
websockets         10.1
wsproto            1.1.0
yarl               1.8.1
youtube-dl         2021.12.17
yt-dlp             2022.8.19
zipp               3.8.1

**Comment by aimarket** [comment]
ok so you accidentally installed the wrong packages try:
`pip uninstall tempmail-py && pip uninstall tempMail`
in the command line

**Comment by CrazyKnifeAim1** [comment]
> ok so you accidentally installed the wrong packages try: `pip uninstall tempmail-py && pip uninstall tempMail` in the command line

aight gonna try

**Comment by CrazyKnifeAim1** [comment]
C:\Users\forst\Downloads\NiggaGenerator (do not share)\DiscordGenerator-main>main.py
Traceback (most recent call last):
  File "C:\Users\forst\Downloads\NiggaGenerator (do not share)\DiscordGenerator-main\main.py", line 9, in <module>
    from TempMail import TempMail
ImportError: cannot import name 'TempMail' from 'TempMail' (unknown location)

**Comment by aimarket** [comment]
share your `pip list` again.

**Comment by CrazyKnifeAim1** [comment]
Package            Version
------------------ -----------
aioconsole         0.5.0
aiofiles           0.6.0
aiohttp            3.7.4.post0
aiosqlite          0.17.0
animec             0.4.2
anyio              3.6.1
appdirs            1.4.4
async-generator    1.10
async-timeout      3.0.1
asyncio            3.4.3
asyncio-extras     1.3.2
asyncpraw          7.5.0
asyncprawcore      2.3.0
attrs              22.1.0
beautifulsoup4     4.11.1
Brotli             1.0.9
bs4                0.0.1
certifi            2022.6.15
cffi               1.15.1
chardet            4.0.0
charset-normalizer 2.1.0
choice             0.1
colorama           0.4.5
discord.py         1.7.3
discord-webhook    0.16.3
discum             1.4.1
disputils          0.2.0
Faker              14.1.0
ffmpeg             1.4
filetype           1.1.0
greenlet           1.1.2
h11                0.12.0
httpcore           0.15.0
httpx              0.23.0
idna               3.3
imageio            2.21.1
importlib-metadata 4.12.0
lxml               4.9.1
MouseInfo          0.1.3
multidict          6.0.2
mutagen            1.45.1
networkx           2.8.5
numpy              1.21.6
opencv-python      4.5.5.64
outcome            1.2.0
packaging          21.3
Paginator          0.5.1
Pillow             9.2.0
pip                22.2.2
playwright         1.22.0
playwright-stealth 1.0.5
PyAutoGUI          0.9.53
pycparser          2.21
pycryptodomex      3.15.0
pyee               8.1.0
pyfade             6.0
pyfiglet           0.8.post1
PyGetWindow        0.0.9
PyMsgBox           1.0.9
pyparsing          3.0.9
pyperclip          1.8.2
pyppeteer          1.0.2
PyRect             0.2.0
PyScreeze          0.1.28
PySocks            1.7.1
python-dateutil    2.8.2
pytweening         1.0.4
PyWavelets         1.3.0
PyYAML             6.0
random-user-agent  1.0.1
requests           2.28.1
requests-toolbelt  0.9.1
rfc3986            1.5.0
rule34             1.8.1
scikit-image       0.19.3
scipy              1.7.3
selenium           4.4.3
setuptools         63.2.0
six                1.16.0
sniffio            1.2.0
sortedcontainers   2.4.0
soupsieve          2.3.2.post1
tempmail-lol       1.1.0
tifffile           2022.8.12
tqdm               4.64.0
trio               0.21.0
trio-websocket     0.9.2
typing_extensions  4.3.0
ua-parser          0.15.0
update-checker     0.18.0
urllib3            1.26.11
websocket-client   0.59.0
websockets         10.1
wsproto            1.1.0
yarl               1.8.1
youtube-dl         2021.12.17
yt-dlp             2022.8.19
zipp               3.8.1

**Comment by CrazyKnifeAim1** [comment]
> share your `pip list` again.

its in there

**Comment by aimarket** [comment]
hmmm `pip install -r requirements.txt` try that

**Comment by CrazyKnifeAim1** [comment]
> pip install -r requirements.txt

i already did

**Comment by aimarket** [comment]
does `pip3 list` give you anything?

**Comment by CrazyKnifeAim1** [comment]
> does `pip3 list` give you anything?

yes the same

**Comment by aimarket** [comment]
Best solution for you is start over because I can't replicate your issue

**Comment by CrazyKnifeAim1** [comment]
> Best solution for you is start over because I can't replicate your issue

i still cannot fix it

**Comment by CrazyKnifeAim1** [comment]
> Best solution for you is start over because I can't replicate your issue

i fixed it myself

**Comment by Vinyzu** [comment]
> > Best solution for you is start over because I can't replicate your issue
> 
> i fixed it myself

Please share your solution ;:D

**Comment by Vinyzu** [comment]
Should be fixxed with newest version.
Update your code.

**Comment by CrazyKnifeAim1** [comment]
> > > Best solution for you is start over because I can't replicate your issue
> > 
> > 
> > i fixed it myself
> 
> Please share your solution ;:D

tempmail is retarded
srry i didnt see it earlier
