### ISSUE TITLE
[ERROR] - Line 192  - initialize() - 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by bingo88-b** [Vinyzu/DiscordGenerator#14]
[ERROR] - Line 192  - initialize() - 'NoneType' object has no attribute 'strip'

What does this mean and how do I fix it..

**Comment by aimarket** [comment]
Getting same error.

**Comment by Nagatochyan** [comment]
same

**Comment by Vinyzu** [comment]
Will be fixxed in todays update

**Comment by Vinyzu** [comment]
Solved in newest version.
Update your cide.
