### ISSUE TITLE
Token locked only when using proxies

### ISSUE THREAD

**Issue by luckyoi** [Vinyzu/DiscordGenerator#17]
So when I'm using proxies, every 3rd or 4th captcha is good but token gets locked every time (tried around 10-15 times)
But when using nonproxy mode, every token is unlocked. premium proxies.

**Comment by luckyoi** [comment]
![image](https://user-images.githubusercontent.com/106918177/185950617-8be29d34-a100-4af2-9645-e64da5353407.png)
You can see AI selected all correct pictures but still said please try again

**Comment by Vinyzu** [comment]
Yes, browser generator needs really HQ Proxies.
They have to have like no flags at all.
Ill close this issue now, cause i cant do anything bout it. You just need even better proxies
