### ISSUE TITLE
Reccomended Proxies?

### ISSUE THREAD

**Issue by ICUBICI** [Vinyzu/DiscordGenerator#2]

**Comment by Vinyzu** [comment]
I already used speedproxies and creativeproxies, both are great.
Currently, most proxies give an error with the gen but im working on a fix alr.

**Comment by Vinyzu** [comment]
Proxies should be supported since Version v.1.0.1
https://github.com/Vinyzu/DiscordGenerator/commit/cf7ba7827b4849f6e0b9a10b1e5a6f252fb59a14

Recommended Services can be seen above.
If you have any proxy issues open another issue
