### ISSUE TITLE
Can you tell format of proxy text file? I am using proxiware Static Proxies

### ISSUE THREAD

**Issue by hasanabbas1278** [Vinyzu/DiscordGenerator#22]
Can you tell in which format can we put proxy ?
When I generated proxy on proxiware, I download whole txt file from website and drag & drop into cmd window where it says to drop. And for the output txt file I also used a empty txt file with output name on it. But when I start it, it goes blind nothing happens waited a lot only black screen.

**Comment by Hn0011** [comment]
Press enter key after opening it should appear if it appears keyboard interruption error then run again and press 2 and enter key

**Comment by hasanabbas1278** [comment]
> 

It didn't work
