### ISSUE TITLE
Can't humanize tokens

### ISSUE THREAD

**Issue by okawsdawfe** [Vinyzu/DiscordGenerator#24]
Getting errors for setting profile picture, hypesquad, bio. Doesn't say why but it doesn't set. What issue could this be?

**Comment by Vinyzu** [comment]
Does it say "Coulnt set Pfp!"?

**Comment by CrazyKnifeAim1** [comment]
> Does it say "Coulnt set Pfp!"?

yes it does

**Comment by Vinyzu** [comment]
The Pfp Api/ discum implementation is kinda broken, were alr working on this but cant do anything bout it rn.
