### ISSUE TITLE
GeneratorExit: Could not get GeoInformation from proxy (Proxy is Invalid/Failed Check)

### ISSUE THREAD

**Issue by omarmoussa69** [Vinyzu/DiscordGenerator#26]
![image](https://user-images.githubusercontent.com/75816758/186544497-3ecfb40c-1da4-4960-b421-b3cb2f343d00.png)
tried different proxies and different formats and I get the same error

**Comment by Vinyzu** [comment]
Ill probably change the service today.

**Comment by Vinyzu** [comment]
Hopefully fixxed with https://github.com/Vinyzu/DiscordGenerator/commit/fba126eef2849b6c1fc80b6d9b1ae8653e565db8 .
If not, i cant do anything bout it.
