### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by SpaceBuddy231** [Vinyzu/DiscordGenerator#33]
Is it possible to use the software with proxies that have a username and password (e.g.: username:password@61.581.684:5800)?

**Comment by Vinyzu** [comment]
Yes, if you paste your proxy like this it should already work.

**Comment by SpaceBuddy231** [comment]
Okay... uh... I have proxies with this format, but it doesn't work. The proxies are formatted exactly in the format given above. Nevertheless, the program displays the following: 
![image](https://user-images.githubusercontent.com/77862882/186989138-85d01d9a-1a44-479d-9010-d950a642ea08.png)

**Comment by Vinyzu** [comment]
Can you add a debugging line:
Like 187: `self.logger.debug(self.proxy.http_proxy)`

**Comment by SpaceBuddy231** [comment]
I have found that some proxies do work. But they are very few. 

In 95% of the cases it looks like this:

![Screenshot 2022-08-27 133351](https://user-images.githubusercontent.com/77862882/187031662-84eb01ef-f1dc-4f10-ab28-578070416bed.jpg)

! (I know that all proxies work quickly.) !

**Comment by 3raden** [comment]
Having the same issue here.

**Comment by Vinyzu** [comment]
> I have found that some proxies do work. But they are very few. 
> 
> In 95% of the cases it looks like this:
> 
> ![Screenshot 2022-08-27 133351](https://user-images.githubusercontent.com/77862882/187031662-84eb01ef-f1dc-4f10-ab28-578070416bed.jpg)
> 
> ! (I know that all proxies work quickly. Actually) !
>  

Is it possible for you to check on the ip api?

**Comment by SpaceBuddy231** [comment]
The website returns  `Acces Denied` for 95% of all proxies. **Nevertheless**, the proxies work without problems on conventional websites like `https://youtube.com`.

![image](https://user-images.githubusercontent.com/77862882/187068332-87645035-a2cb-4f3c-af73-d83694b8cba8.png) 

^^^^^^^^^ **SAME PROXY** ^^^^^^^^^

![image](https://user-images.githubusercontent.com/77862882/187068374-94cd28d8-78da-42aa-bd01-957a15a7132f.png)

**Comment by Vinyzu** [comment]
Ok, this explains things. Can you check other ip-check (apis) if the aldo block ur proxy?

**Comment by Vinyzu** [comment]
Hopefully fixxed in v1.0.6
https://github.com/Vinyzu/DiscordGenerator/commit/d32ac63a4ed505a9bd433357f86af83bebbdd1e5
