### ISSUE TITLE
How can i train a model with captcha pictures?

### ISSUE THREAD

**Issue by searchingforcode** [Vinyzu/DiscordGenerator#34]
Hi thanks for the wonderful work. How can i train a model with captcha pictures? You didn't specify any instructions about training a model. Can you please write some instructions about model training?

**Comment by Vinyzu** [comment]
Can you please dm me on discord, as this isnt a Repo related question and you could help me/us.
Vinyzu#1470

**Comment by searchingforcode** [comment]
> Can you please dm me on discord, as this isnt a Repo related question and you could help me/us. Vinyzu#1470

Hi thanks i will dm you on discord. Thanks

**Comment by Vinyzu** [comment]
Did u dmed me alr? Lol

**Comment by searchingforcode** [comment]
Hi yes just dmed you
