### ISSUE TITLE
Joining servers automatically

### ISSUE THREAD

**Issue by 3raden** [Vinyzu/DiscordGenerator#36]
Are you able to make them join servers automatically?

**Comment by Vinyzu** [comment]
Its pretty easy to code for you, or you can use external tools.
If u really want it you can join my server and make a vote, if it gets enough upvotes ill do it

**Comment by Vinyzu** [comment]
Added in v1.0.6
https://github.com/Vinyzu/DiscordGenerator/commit/d32ac63a4ed505a9bd433357f86af83bebbdd1e5
