### ISSUE TITLE
[Invite]

### ISSUE THREAD

**Issue by devitystudio** [Vinyzu/DiscordGenerator#37]
Just to say:
**Discord server invite has expired.**
Awsome job. Im just having a little trouble adding proxyes, Dont know why.

**Comment by Vinyzu** [comment]
Thanks for pointing out.
Fixxed in v1.0.6
https://github.com/Vinyzu/DiscordGenerator/commit/d32ac63a4ed505a9bd433357f86af83bebbdd1e5
