### ISSUE TITLE
import err

### ISSUE THREAD

**Issue by plaraje** [Vinyzu/DiscordGenerator#38]
D:/myFolder/hcaptcha_challenger\solutions\resnet.py", line 13, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by Vinyzu** [comment]
Did you installed all the requirements?
`pip install -r requirements.txt`

**Comment by plaraje** [comment]
> Did you installed all the requirements? `pip install -r requirements.txt`

yes but it says yaml is not a module

**Comment by Vinyzu** [comment]
Yes the module is pyyaml
`pip install pyyaml`

**Comment by plaraje** [comment]
thanks, yaml is installed but note that i installed requeriments but i still need to install lots of packages manually

**Comment by Vinyzu** [comment]
Wdym? Which packages?

**Comment by plaraje** [comment]
> Wdym? Which packages?

some modules that werent in requeriments.txt

**Comment by Vinyzu** [comment]
> > Wdym? Which packages?
> 
> some modules that werent in requeriments.txt

@plaraje list them please

**Comment by plaraje** [comment]
> > > Wdym? Which packages?
> > 
> > 
> > some modules that werent in requeriments.txt
> 
> @plaraje list them please

Sorry i dont remember the modules and im lazy to try in a new vm, you can also do that, im in windows if its helpful  for you
