### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by Pratikk1337** [Vinyzu/DiscordGenerator#39]
[ERROR] - Line 188  - initialize() - Proxy Check Failed: Could not get GeoInformation from proxy (Proxy is Invalid/Failed Check)

**Comment by Vinyzu** [comment]
Your proxy is invalid, if your convinced its not check if it can connect to https://api.my-ip.io/ip

If not, also check https://jsonip.com/ (this will be used in next version)

**Comment by Vinyzu** [comment]
Hopefully fixxed in v1.0.6
https://github.com/Vinyzu/DiscordGenerator/commit/d32ac63a4ed505a9bd433357f86af83bebbdd1e5
