### ISSUE TITLE
Discord token login

### ISSUE THREAD

**Issue by hoangthangbk51** [Vinyzu/DiscordGenerator#4]
Please suport for discord token login . 
Thanks for nice project .

**Comment by Vinyzu** [comment]
It is already code up.
(You can see i commented out at the end of the Generator Class)
I wonder ehy you would want to use it tho?
(You wouldnt be able to do anything with it)

**Comment by hoangthangbk51** [comment]
> It is already code up.
> (You can see i commented out at the end of the Generator Class)
> I wonder ehy you would want to use it tho?
> (You wouldnt be able to do anything with it)

Thanks for your reply.
Im a amateur program . and would like to learn how to web automation. I was try some project with captcha slover . But your project very smooth. Somthing i want to do also is sent data from txt and from line by line not on random data. Do you give me some suggestions. This is Multithreading and very new to me .Thanks for support. 
.

**Comment by Vinyzu** [comment]
Sorry, i couldnt 100% understand your comment 😅.
(For example what you mean with the line from line reading and "execution"?)
But i would recommend you to start with selenium, because its easier to learn and had a larger community/more code to work/lean on.

**Comment by hoangthangbk51** [comment]
Hi. What i mean is if you have the "proxy.txt" file . And i would like to use :
thread1 use proxy on line number 1 on the "proxy.txt"
Thread2 use proxy on line number 2 on the "proxy.txt"

Something like that. 
Thanks you so much.

**Comment by Vinyzu** [comment]
Yes, thats possible of course

**Comment by hoangthangbk51** [comment]
Can you give me some samples code . 
Thanks . Im stuck on that now.

**Comment by Vinyzu** [comment]
Well, it depends on the code ur working with already ofc.
in my code, it would look something like
```py
while True:
        threadz = []
        for _ in range(threads):
            proxy = proxies[_] # See the edit here
            threadz.append(Generator().initialize(
                proxy, mode, output_file, email, humanize))

        await asyncio.gather(*threadz)
        await asyncio.sleep(2)
```
However, ill close this issue with this, because this is not a coding helping/learning platform.
