### ISSUE TITLE
tokens get locked

### ISSUE THREAD

**Issue by Vamp999** [Vinyzu/DiscordGenerator#42]

**Comment by Vamp999** [comment]
they all get locked as soon as i make them

**Comment by SpaceBuddy231** [comment]
same

**Comment by Vinyzu** [comment]
On which step?
After the Captcha?
Are your proxy of High Quality?
Please provide more info.

**Comment by ItsCEED** [comment]
Most likely the solver is patched.

**Comment by Vinyzu** [comment]
I dont think so, because Dislock uses a hq mouse movement generator. From what i already saw, discord just got better at detecting proxies.

**Comment by ItsCEED** [comment]
> I dont think so, because Dislock uses a hq mouse movement generator. From what i already saw, discord just got better at detecting proxies.

Fully reversed hsl/hsw gens are still working.

One thing that is possible is ip leaking. Browsers tend to do that

**Comment by Vamp999** [comment]
They get locked after the Captcha and when i use my proxies it gives me an error.

**Comment by Vinyzu** [comment]
> They get locked after the Captcha and when i use my proxies it gives me an error.

Can u paste the error here please

**Comment by Vinyzu** [comment]
> > I dont think so, because Dislock uses a hq mouse movement generator. From what i already saw, discord just got better at detecting proxies.
> 
> Fully reversed hsl/hsw gens are still working.
> 
> One thing that is possible is ip leaking. Browsers tend to do that

Mh, ill have a read bout that

**Comment by Vinyzu** [comment]
Confirmed:
At the Current version, Dislock leaks the true IP (when you use a proxy) through webRTC. 
I solved the issue already and it will be fixxed in the next version. Thanks @ItsCEED ;:D

**Comment by SpaceBuddy231** [comment]
> Confirmed: At the Current version, Dislock leaks the true IP (when you use a proxy) through webRTC. I solved the issue already and it will be fixxed in the next version. Thanks @ItsCEED ;:D

When will the fixed version be published?

**Comment by Vinyzu** [comment]
Idk tbh, maybe 2-3 days, mby a week

**Comment by SpaceBuddy231** [comment]
> Idk tbh, maybe 2-3 days, mby a week

....

**Comment by ItsCEED** [comment]
> > Idk tbh, maybe 2-3 days, mby a week
> 
> ....

as im running modded version with the Leak on, i assume your IP's are just bad and its not the tool to blame
