### ISSUE TITLE
The emails are invalid

### ISSUE THREAD

**Issue by Discordbotdashboard** [Vinyzu/DiscordGenerator#43]

**Comment by Vinyzu** [comment]
I noticed, me and another dude are already working on a long lasting solution.
For now use the unverified option

**Comment by floconacs** [comment]
I added the .com at the end of the mail, the account is well generated but it is blocked by the verification ....

**Comment by uf576d** [comment]
> I noticed, me and another dude are already working on a long lasting solution. For now use the unverified option

u most likely need to use a new api from a different temp mail like i think u can use https://rapidapi.com/johndevz/api/gmailnator because it generates @gmail.com accounts and has an api.

**Comment by Vinyzu** [comment]
No, u dont need one.
A guy set up some custom domains for me, and the TempMailApi now supports cudtom domains.
What were gonna do is release some of our custom emails one at a time, wait for discord to ban them and then go on with the next few.

**Comment by ItsCEED** [comment]
> > I noticed, me and another dude are already working on a long lasting solution. For now use the unverified option
> 
> u most likely need to use a new api from a different temp mail like i think u can use https://rapidapi.com/johndevz/api/gmailnator because it generates @gmail.com accounts and has an api.

Gmailnator produces dot/plus/dash trick gmails which are banned long ago on discord.
If you really wanna go with that junk, just grab few emails of your own (more characters in it the better), and go ham with them.

**Comment by uf576d** [comment]
> No, u dont need one. A guy set up some custom domains for me, and the TempMailApi now supports cudtom domains. What were gonna do is release some of our custom emails one at a time, wait for discord to ban them and then go on with the next few.

when r u updating?

**Comment by FuckingToasters** [comment]
Custom Domains work fine. I own a .gay domain which is a catchall and can create discord account with it without any issue.

**Comment by FuckingToasters** [comment]
> > I noticed, me and another dude are already working on a long lasting solution. For now use the unverified option
> 
> it have something to do with the email not having .com at the end discords email api thingo prolly doesnt accept emails that dont finish in .com like when i use a .com email from tempmail.lol its fine but when i use some weird one it doesnt work

That's wrong. I used a own domain and changed the code a bit so it can use own domains because i thought that the issue is the tld (.com, .gay etc.) i then used a domain which have .gay as tld and it worked fine when i use improvmx dns settings to make it to a captchall mail but when i changed the dns settings to the ones from tempmail.lol it show the mail as invalid.

So the issue isn't the tld, it has something to do with the dns settings.

**Comment by FuckingToasters** [comment]
> > > > I noticed, me and another dude are already working on a long lasting solution. For now use the unverified option
> > > 
> > > 
> > > it have something to do with the email not having .com at the end discords email api thingo prolly doesnt accept emails that dont finish in .com like when i use a .com email from tempmail.lol its fine but when i use some weird one it doesnt work
> > 
> > 
> > That's wrong. I used a own domain and changed the code a bit so it can use own domains because i thought that the issue is the tld (.com, .gay etc.) i then used a domain which have .gay as tld and it worked fine when i use improvmx dns settings to make it to a captchall mail but when i changed the dns settings to the ones from tempmail.lol it show the mail as invalid.
> > So the issue isn't the tld, it has something to do with the dns settings.
> 
> Yes i figured a week ago discord doesnt ban domains, they ban ips of mx server of the domains. For example, tempmail.lol did use all the same ip for their `mx.domainname.toplevel-domain`, and discord just banned all domains with the same ip of the mx mail server.

Do you know any workaround for this? I thought about self hosting it so you use the IP of your own Linux Server but i guess that's too complicated for the persons using this code (lot of skids here) and you need to understand a bit javascript for self hosting aka read errors cause i tried it and go tlot of different errors which need to be solved. You basically only would need to use another IP and even if you ask the developers of tempmaillol i don't think they set a new ip and even if they do, discord is blocking them again.

**Comment by Vinyzu** [comment]
Fixxed in newest version v2.0: https://github.com/Vinyzu/DiscordGenerator/commit/756939fa6a02453a54691ec398971f1f8f67eacf
