### ISSUE TITLE
The AI doesn't supports captcha's with birds and Cats

### ISSUE THREAD

**Issue by kiketi9a** [Vinyzu/DiscordGenerator#48]
The AI doesn't supports captcha's with birds and Cats
![ForGit](https://user-images.githubusercontent.com/112905729/188514869-e1b41763-9257-4ab6-b363-1138d0e8ee31.PNG)

**Comment by ItsCEED** [comment]
read.

**Comment by Vinyzu** [comment]
Gonna be fixxed in new update (Automatic Ai Updates)
