### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by fdsggfd** [Vinyzu/DiscordGenerator#49]
"Could not get GeoInformation from proxy (Proxy is Invalid/Failed Check"
Everytime despite using good proxy

**Comment by Vinyzu** [comment]
What proxy type and format are you using?

**Comment by fdsggfd** [comment]
> What proxy type and format are you using?

hi. Im using https. http and ive tried socks5 too with ip:port format. Ive noticed it doesnt show the error if i used other proxies that have username and password in the format

**Comment by fdsggfd** [comment]
im not a programmer i dont know coding but i was thinking its probably the way the proxy format is split and then loaded onto http://ip-api.com/json/

**Comment by Vinyzu** [comment]
It should actually.
Did u remove the http:// / https:// in front of the proxy?

**Comment by fdsggfd** [comment]
yes i did remove it. format is just ip:port but have a look at  this: (random ip addresses)
http://ip-api.com/json/37.99.224.225:7497
http://ip-api.com/json/37.99.224.225

the request with :port is invalid for some reason

**Comment by Vinyzu** [comment]
Oh ok ill have a look

**Comment by FuckingToasters** [comment]
I hope that helps, this is the proxysupport code i made a while ago for my discord phone verifier. 
```py
import pystyle
class loadproxyclass:
    def loadproxy(self, proxytype):
        with open("files/proxies.txt", "r") as proxy_file:
            proxies = proxy_file.read().splitlines()
            proxy_split = "None"
            for proxy in proxies: proxy_split = proxy.split(":")
            try:
                host_name, port, username, password = proxy_split[0], proxy_split[1], proxy_split[2], proxy_split[3]
                proxy_formatted = f"{proxytype}://{username}:{password}@{host_name}:{port}"
                if proxytype != "": proxyauth = {"all://": proxy_formatted}
                else: proxyauth = {"all://": None}

            except IndexError:
                try:
                    host_name, port = proxy_split[0], proxy_split[1]
                    proxy_formatted = f"{proxytype}://{host_name}:{port}"
                    if proxytype != "": proxyauth = {"all://": proxy_formatted}
                    else: proxyauth = {"all://": None}

                except IndexError:
                    pystyle.Write.Print("\t[*] Proxies inside files/proxies.txt are not formatted correctly (IP:PORT or IP:PORT:USER:PASS)!\n", pystyle.Colors.yellow, interval=0)
                    proxyauth = {"all://": None}
            
            return proxyauth
```
Code is located here for refrence: https://github.com/FuckingToasters/discord-phone-verifier/blob/main/new%20version/plugins/filesupport/proxy.py

**Comment by Vinyzu** [comment]
Should be fixxed in newest version v2.0: https://github.com/Vinyzu/DiscordGenerator/commit/756939fa6a02453a54691ec398971f1f8f67eacf

If not, create an issue at the Botright project.
