### ISSUE TITLE
Error while solving captcha

### ISSUE THREAD

**Issue by SaN-Tools** [Vinyzu/DiscordGenerator#5]
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:709: error: (-215:Assertion failed) model_proto.has_graph() in function 'cv::dnn::dnn4_v20211220::ONNXImporter::populateNet'

**Comment by Vinyzu** [comment]
I reported this issue to the creator of the ai
https://github.com/QIN2DIM/hcaptcha-challenger/issues/140

Im not sure why it occours, but it seems like u can fix it by doenloading the onnx files in his model realease tab.

**Comment by SaN-Tools** [comment]
ok ty i will try

**Comment by Vinyzu** [comment]
Solved with v.1.0.2
https://github.com/Vinyzu/DiscordGenerator/commit/8dde3181620ccbb4dcd022b6a9b98607d8a10cb9
