### ISSUE TITLE
need help?

### ISSUE THREAD

**Issue by Altify-Development** [Vinyzu/DiscordGenerator#50]
I made a fake person generator, which in its process, creates discord accounts on revolving internal proxies using tor servers. I can probably integrate that into this so the users don't need to use proxies. I would also make a more compatible GUI and auto-installer, updater, and informaticon to improve user-returns and help fix bugs. hmu Altify#0001

**Comment by Altify-Development** [comment]
[Fake Person Generator](https://altify-developing-001.netlify.app/?dest=person_generator)
majorly opensrc but some parts are compiled to protect keys and server data ( i.e nameservers:ports that are hosted from my server room ) go to releases for compiled version of the generator, and it is a wip so don't expect everything to be flawless, but one "person" amounts to everything they would ever have, need, and their personalization.

Here is a complete list of everything it generates about any single person:
```
Computer settings
Username
Random name
Will be used for most accounts/passwords
Computername
Random string or personalized
PIN
Randomized or personalized 4 numeral digit code
Microsoft Account
Fake account
Product Activation Key
Google Hosted data
Saved Password
History
Bookmarks
Autofills
Credit Cards
Discord Tokens
Game Info Grabber
Steam
Minecraft
UPlay
Battle.NET
Social Messaging Information
Discord
Telegram
Skype
Outlook
Personal Data
Life Insurance
Health Coverage
Dental
GUI save option
Creating a gui background
Defaulting and Defaults setup ( .ini )
Passport
Enhanced Credit Card Information
blacklist detection ( checks if mac address is blocked by my application i.e if I banned the mac address )
```

**Comment by Vinyzu** [comment]
Ok, but how can i help you? I dont know this ahk coding language so i cant chrck any of your code.
If you want to contribute to this project, just open a pr (to fix bugs for example)

**Comment by Altify-Development** [comment]
k ill get to work on a new version for this generator

**Comment by Altify-Development** [comment]
about 50% done contact me on discord Altify#0001 ill keep you updated from there so you can close this issue.
