### ISSUE TITLE
Email Issue

### ISSUE THREAD

**Issue by DarkSuffer01** [Vinyzu/DiscordGenerator#51]
Your email api was patched by discord, a g a i n
![image](https://user-images.githubusercontent.com/107288467/189350993-ef811a38-2042-49d2-a52b-22288636cdb2.png)
When's the unpatch?

**Comment by Vinyzu** [comment]
https://github.com/Vinyzu/DiscordGenerator/issues/43

Were already fixxing it, next release is close to done.
