### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by DeratonTrix** [Vinyzu/DiscordGenerator#54]
![image](https://user-images.githubusercontent.com/94805186/189536183-daabd4d3-ce1f-4f69-954e-5230272db670.png)
everytime i drag and drop my proxy file there is just crashes

**Comment by Vinyzu** [comment]
What lol
What command line tool are you using?

**Comment by DeratonTrix** [comment]
idk what u fully mean by that but the lines i press is 

1, 1, 1 and for thread 1 and then i try dragging in the proxy file and pressing enter it just crashes

**Comment by Vinyzu** [comment]
Do u get an error?

**Comment by DeratonTrix** [comment]
ye but it insta closes so cant see the error tho just see text spamming and then it closes with like 0.5 sec between it

**Comment by DeratonTrix** [comment]
if u want ill add u on discord and screenshare to u

**Comment by DeratonTrix** [comment]
Trix#4200 add me on discord

**Comment by Vinyzu** [comment]
> ye but it insta closes so cant see the error tho just see text spamming and then it closes with like 0.5 sec between it

Open in with cmd and execute from there then you can see the error

**Comment by DeratonTrix** [comment]
Traceback (most recent call last):
  File "C:\Users\solem\Downloads\DiscordGenerator-main\DiscordGenerator-main\main.py", line 1129, in <module>
    asyncio.run(main())
  File "C:\Users\solem\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\solem\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\solem\Downloads\DiscordGenerator-main\DiscordGenerator-main\main.py", line 1080, in main
    raise ValueError("Provided ProxyPath isnt a file!")
ValueError: Provided ProxyPath isnt a file!

**Comment by Vinyzu** [comment]
Can u send me a screenshot before you press enter when draging the proxy file?

**Comment by DeratonTrix** [comment]
![image](https://user-images.githubusercontent.com/94805186/190254687-c713c73e-85f5-4252-8d1d-e0052e1b4e9b.png)

**Comment by Vinyzu** [comment]
Ah ok you have to remove the " infront and behind of the path.

**Comment by FuckingToasters** [comment]
> Ah ok you have to remove the " infront and behind of the path.

Almost correct, the "" are used to put a path with spaces together. without them it would see them as seperate attributes. However the way he implemented the "" is wrong. Instead of wrapping the full path in these "" he need to do it for the file only so `C:\Users\x\Downloads\"Text Document.txt"`
