### ISSUE TITLE
AttributeError: 'str' object has no attribute 'sender'

### ISSUE THREAD

**Issue by FuckingToasters** [Vinyzu/DiscordGenerator#58]
Hi, i edited the code a bit so it use the private custom domain feature instead of the public ones which are provided though the official API.
I've only edited tempmail.py and this issue apper in main.py on line 929.
I'm not sure how i can solve this one, maybe anyone can help me there. thx in adance!
````py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DISLOCK\main.py", line 671, in generate_unclaimed
    email_v = await self.confirm_email()
  File "C:\Users\Administrator\Desktop\DISLOCK\main.py", line 929, in confirm_email
    if "mail.discord.com" in str(mail.sender):
AttributeError: 'str' object has no attribute 'sender'
```

**Comment by Vinyzu** [comment]
Can you provide your full tempmail.py?

**Comment by Vinyzu** [comment]
Should be fixxed in newest version v2.0: https://github.com/Vinyzu/DiscordGenerator/commit/756939fa6a02453a54691ec398971f1f8f67eacf
