### ISSUE TITLE
install playwright

### ISSUE THREAD

**Issue by PineapleTeam** [Vinyzu/DiscordGenerator#6]
can someone please help me why i always cannot install playwright, i already try search on google but it still the same
![Desktop Screenshot 2022 08 20 - 15 39 17 14 (2)](https://user-images.githubusercontent.com/67152028/185736732-63f14448-8c49-4c77-aec8-d2315cdc16c9.png)

**Comment by Vinyzu** [comment]
Try executing
`python3 -m pip install --force-reinstall playwright`
In a adminstrative command prompt.

**Comment by PineapleTeam** [comment]
![Desktop Screenshot 2022 08 20 - 15 53 05 91](https://user-images.githubusercontent.com/67152028/185737321-b4b272ca-ef4d-49c6-9102-d0162bed6373.png)

**Comment by Vinyzu** [comment]
Do you see the yellow warning in your last message,
It says it cant add to path. You maight wanna add the given folderpath to ur path (/enviroment variables)

**Comment by PineapleTeam** [comment]
Okay I will try it thanks btw

Pada tanggal Sab, 20 Agu 2022 16.09, Vinyzu ***@***.***>
menulis:

**Comment by PineapleTeam** [comment]
I got it thanks btw

**Comment by Vinyzu** [comment]
No Problem, if you have an other problems feel free to open another issue!
