### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vamp999** [Vinyzu/DiscordGenerator#61]
![image](https://user-images.githubusercontent.com/98104219/190851338-654a0c79-3b4e-400d-9cbb-695821899580.png)

How to fix this?

**Comment by FuckingToasters** [comment]
It litally say you want to do... Run `playwright install`

**Comment by Vamp999** [comment]
i did that but it does not work 🤦‍♂️

**Comment by Vamp999** [comment]
![image](https://user-images.githubusercontent.com/98104219/190857241-a44659ed-19bb-4e72-8fe1-13c615ee56c7.png)

am i doing something wrong?

**Comment by Vinyzu** [comment]
No error/message at all?
Maybe your antivirus?

**Comment by Vamp999** [comment]
> No error/message at all? Maybe your antivirus?

it works now my anti virus deleted some files that gave me that error thanks!

**Comment by Vinyzu** [comment]
No problem, glad i could help!
