### ISSUE TITLE
cant open main.py 

### ISSUE THREAD

**Issue by DeratonTrix** [Vinyzu/DiscordGenerator#63]
when i do pip install -r requirements.txt i get 
ERROR: Could not find a version that satisfies the requirement botright~=1.0 (from versions: 0.1.0, 0.1.0.1, 0.1.1)
ERROR: No matching distribution found for botright~=1.0
help me please

**Comment by DeratonTrix** [comment]
@Vinyzu

**Comment by Vinyzu** [comment]
Fixxed

**Comment by DeratonTrix** [comment]
huh

**Comment by DeratonTrix** [comment]
thx
