### ISSUE TITLE
cant gen

### ISSUE THREAD

**Issue by DeratonTrix** [Vinyzu/DiscordGenerator#66]
okay so when i open main.py it opens a web and everything its supposed to but before it can be generated it takes and opens another web so it just gets limited and doesnt gen any accs

**Comment by DeratonTrix** [comment]
i have thread 1

**Comment by Vinyzu** [comment]
Error code?

**Comment by DeratonTrix** [comment]
there is no error code do u have discord so i can add u and screen share to u

**Comment by Vinyzu** [comment]
Its linked in the readme, no screenshare, just record a video and send it to me

**Comment by DeratonTrix** [comment]
i cant find anything where i can send it to u

**Comment by DeratonTrix** [comment]
nvm

**Comment by DeratonTrix** [comment]
i sent it to u on discord

**Comment by DeratonTrix** [comment]
@Vinyzu

**Comment by Vinyzu** [comment]
Yes?

**Comment by DeratonTrix** [comment]
Did u see the vid i sent u on discord

**Comment by Vinyzu** [comment]
Whats your dc username?

**Comment by DeratonTrix** [comment]
Trix#4200

**Comment by Vinyzu** [comment]
Solved (Not solved but yes)
