### ISSUE TITLE
Proxy Problems

### ISSUE THREAD

**Issue by CTB64YT** [Vinyzu/DiscordGenerator#68]
Hello, im trying to use HTTP proxies with Dislock, but theres a issue. when ever i put my proxies in it, it doesnt work. but without proxies it does work. for some reason.

**Comment by CTB64YT** [comment]
It doesnt give any errors too, it just stops and come backs to CMD

**Comment by Vinyzu** [comment]
Its your proxy, or your proxy format. The error isnt shown cause i forgot smthng
