### ISSUE TITLE
Captcha didn't load

### ISSUE THREAD

**Issue by PineapleTeam** [Vinyzu/DiscordGenerator#7]
![Desktop Screenshot 2022 08 20 - 17 30 51 63](https://user-images.githubusercontent.com/67152028/185742292-c7a6c124-176a-466a-9924-d80aefa78f35.png)

**Comment by PineapleTeam** [comment]
do i need to buy a proxy?

**Comment by Vinyzu** [comment]
Yes this is a know issue because it doesnt tick the checkbox.
Ill fix this today

**Comment by Vinyzu** [comment]
> do i need to buy a proxy?

No, u just need to wait or use the unclaimed

**Comment by PineapleTeam** [comment]
can u make the captcha solver from anti-captcha.com or 2captcha.com because i see you got a problem with the AI, i know it needs money to solve the captcha but i think it was cheap like just 1$ you can get 1000 captcha

**Comment by Vinyzu** [comment]
No.
I wouldnt spend a month implementing ai to then use a captcha service

**Comment by PineapleTeam** [comment]
well i will wait for the update i guess, thanks mate
