### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Mewzax** [Vinyzu/DiscordGenerator#71]
yay a friend sent me your project: botright
i did not see this repo so i made my own gen and my own mail verificator (unbannable domain + free) and i made tokens
then i saw this lmfao im so dumb
really nice project (there are some issues but its cool) ! also botright is the best py browser i have ever seen in my ridiculous life
Keep up the good work tysm <3

**Comment by Vinyzu** [comment]
Thanks mate!
