### ISSUE TITLE
ProxyCheckError

### ISSUE THREAD

**Issue by fdsggfd** [Vinyzu/DiscordGenerator#73]
AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\proxy_manager.py", line 95, in check_proxy
    raise ProxyCheckError(
botright.modules.proxy_manager.ProxyCheckError: Could not get GeoInformation from proxy (Proxy is Invalid/Failed Check)

**Comment by Vinyzu** [comment]
Are you sure your proxy works?
Whats your proxy format?

**Comment by fdsggfd** [comment]
the proxy format is ip:port
my proxies work ive checked them in multiple different websites

**Comment by Vinyzu** [comment]
Weird

**Comment by Vinyzu** [comment]
Please reopen this issue on my botright github.
