### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by TheCannard38** [Vinyzu/DiscordGenerator#8]
where doi put my proxies

**Comment by Vinyzu** [comment]
You have to create a txt file where u paste them, then drag and drop the txt into the input field.

**Comment by TheCannard38** [comment]
"captcha didnt load" any idea ?

**Comment by Vinyzu** [comment]
Probably your proxy beeing slow. Ill update again today raising the timeouts.

**Comment by Vinyzu** [comment]
Timeouts has been set higher.
Update your code and try again
