### ISSUE TITLE
Where can i put in proxies

### ISSUE THREAD

**Issue by RealMaMo1086** [Vinyzu/DiscordGenerator#83]
i dont know how to put proxies in

**Comment by fdsggfd** [comment]
create a file and save it in the same directory as main.py (call it proxy.txt to make it easy). in the file enter your proxies in either IP:PORT format or USER:PASS IP:PORT format and then when the programme asks for it just type proxy.txt

**Comment by Vinyzu** [comment]
^^
But just two things:
1. Use username:password@ip:port
2. you can just create a txt anywhere and Drag&Drop it into cmd when asked for it.
