### ISSUE TITLE
output.txt not updating

### ISSUE THREAD

**Issue by luckyoi** [Vinyzu/DiscordGenerator#9]
Script generates the token and everything and just closes the console leaving output.txt empty. First time it worked sucessfuly but now it won't update output.

**Comment by Vinyzu** [comment]
Can you give me the settings/inputs you used?

**Comment by Vinyzu** [comment]
Should be fixxed in update v.1.0.4

https://github.com/Vinyzu/DiscordGenerator/commit/1fe79ca3c3565b171578b0b9d87f3e7cb495dacb
